### ISSUE TITLE
Mod crashing on startup

### ISSUE THREAD

**Issue by Egorkuz211** [Cannoneers-of-Create/CreateBigCannons#220] opened 2023-05-26 16:50 UTC
Starting minecraft with this mod leads to some kind of "null" exception and crash. Tried starting on both 1.19.2 and 1.18.2. Same error happens when starting "steam and rails". Create alone works fine.

**Comment by Egorkuz211** [comment] 2023-05-27 01:46
True, problem is in incompatibility with Create 0.5.1.

**Comment by rbasamoyai** [comment] 2023-06-01 14:40
Planned and in the works

**Comment by rbasamoyai** [comment] 2023-06-01 14:40
actually, will leave this issue hanging until we are really sure it works

**Comment by BraveCaperCat2** [comment] 2023-07-21 09:43
you are messing up the issues page, please close this as it is a duplicate of #221

**Closed as completed** 2023-08-04 18:10 UTC
