### ISSUE TITLE
Endless projectile impacts effect happens and projectile doesn't disappear when shoot at VS ship

### ISSUE THREAD

**Issue by CryJoyYarn** [Cannoneers-of-Create/CreateBigCannons#617] opened 2024-07-23 06:39 UTC
1.18.2 CBC 5.5.0
VS 2.1.1 Beta5
Forge 40.2.21
Problem doesn't exist on CBC 5.4.0
When shoot at ground, projectile acts and disappears normally. When shoot at VS ship, projectile stuck on it and cause endless projectile impacts, never disappear.
![2024-07-23_14 25 54](https://github.com/user-attachments/assets/bec1ad4c-36af-4f75-ba98-1558e2a25021)
![2024-07-23_14 31 28](https://github.com/user-attachments/assets/c2e9cc92-9300-4b4c-baa5-551eb8811846)

**Comment by CryJoyYarn** [comment] 2024-07-23 06:46
Oh, correction. On CBC 5.4.0 projectile will slowly sink to ground after hit on VS ship.
![2024-07-23_14 44 23](https://github.com/user-attachments/assets/b9d3daa9-0b68-4472-804f-6c45a2ec2f7f)

**Comment by rbasamoyai** [comment] 2024-07-23 23:56
The issue is that VS ships are not factored into ground collision checks.

In my opinion this is a VS issue, so closing as not going to fix.

**Comment by rbasamoyai** [comment] 2024-07-23 23:57
Please report this to the VS devs.

**Closed as not planned** 2024-07-23 23:57 UTC
