### ISSUE TITLE
crashes because it says it needs flywheel 0.6.9 but that doesn't exit??

### ISSUE THREAD

**Issue by MRwhineglass** [Cannoneers-of-Create/CreateBigCannons#255] opened 2023-07-18 12:24 UTC

**Comment by MRwhineglass** [comment] 2023-07-18 12:36
it says this: [main/ERROR] Missing or unsupported mandatory dependencies:	Mod ID: 'flywheel', Requested by: 'create', Expected range: '[0.6.9,0.6.10)', Actual version: '0.6.8.a'

**Comment by BraveCaperCat2** [comment] 2023-07-21 09:38
This is an issue with create.

**Comment by wardeada** [comment] 2023-07-22 04:55
como puedo instalar los mods correcta mente o un link de un tutorial de como instalarlo

**Comment by HonzaVinCZ** [comment] 2023-07-24 04:16
0.6.9 exists but it's only on maven now. However Create Big Cannons doesn't work with either Create 0.5.1 or Flywheel 0.6.9 so now it's unplayable. 
https://maven.tterrag.com/com/jozufozu/flywheel/

**Comment by BraveCaperCat2** [comment] 2023-07-24 15:07
> 0.6.9 exists but it's only on maven now. However Create Big Cannons doesn't work with either Create 0.5.1 or Flywheel 0.6.9 so now it's unplayable. https://maven.tterrag.com/com/jozufozu/flywheel/

Would like to note that if create doesn't include flywheel 0.6.9 itself (like it should be) then it's create's fault. although i didn't know that flywheel 0.6.9 is incompatible with BigCannons.

**Comment by BraveCaperCat2** [comment] 2023-07-26 10:49
close this issue it is a duplicate of #221

**Comment by HonzaVinCZ** [comment] 2023-07-28 08:31
> > 0.6.9 exists but it's only on maven now. However Create Big Cannons doesn't work with either Create 0.5.1 or Flywheel 0.6.9 so now it's unplayable. https://maven.tterrag.com/com/jozufozu/flywheel/
> 
> Would like to note that if create doesn't include flywheel 0.6.9 itself (like it should be) then it's create's fault. although i didn't know that flywheel 0.6.9 is incompatible with BigCannons.

Since Create 0.5.1 Flywheel is included inside the mod file itself. So no need to download Flywheel and Create separately. Found out lately. This mod needs an update to make it compatible now.

**Closed as completed** 2023-08-04 16:34 UTC
