### ISSUE TITLE
Cannot load world because of Create Big Cannons Error

### ISSUE THREAD

**Issue by tartyto** [Cannoneers-of-Create/CreateBigCannons#433] opened 2023-12-31 22:28 UTC
It first crashed after firing a cannon on a cannon carriage and then the same crash happens when loading the world, i lost that world.
It says:

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot read field "f_74676_" because "breech" is null

[Crash Log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13802311/log.txt)

**Comment by rbasamoyai** [comment] 2023-12-31 22:33
Duplicate of #427, fixed and will be closed on 0.5.3.b release

**Closed as completed** 2024-01-01 21:35 UTC
Labels: To be closed on next release
