### ISSUE TITLE
[MINOR] Incorrect particles and projectile ballistics

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#45] opened 2022-07-29 11:22 UTC
To reproduse:
1. Cannon Pitch ~20° (CannonPitch: 19.987497f).
2. Cannon must be 14 blocks length (Projectile length: 8 blocks).
3. Cannon must be made of steel.
![2022-07-29_13 12 38](https://user-images.githubusercontent.com/109973204/181748196-c8005447-1d91-4f25-813d-02da61f634eb.png)

**Comment by rbasamoyai** [comment] 2022-07-29 14:29
Duplicate of https://github.com/rbasamoyai/CreateBigCannons/issues/17, but essentially Minecraft cannot handle high-velocity entities. I've mentioned in that issue that I would like to eventually switch to a non-entity based projectile system, but for now this is just something that is not that urgent right now.

**Closed as completed by rbasamoyai** 2022-07-29 14:29 UTC
Labels: bug, duplicate
