### ISSUE TITLE
null thingy

### ISSUE THREAD

**Issue by yolobroooooo** [Cannoneers-of-Create/CreateBigCannons#231] opened 2023-06-10 12:36 UTC
(sent this on discord)
i am on uh 1.19.2 forge
version createbigcannons-forge-1.19.2-0.5.1.a-nightly-02d9581.jar
java.lang.reflect.InvocationTargetException: null

i have 117 mods installed (excluding [cbc)](url)

https://github.com/Cannoneers-of-Create/CreateBigCannons/files/11712436/crash-2023-06-10_20.26.01-fml.1.txt

**Comment by rbasamoyai** [comment] 2023-06-10 13:18
Duplicate of #230

**Closed as completed** 2023-06-10 13:18 UTC
